### PR TITLE
Add "join table" for visits

### PR DESCRIPTION
**Pull request by utsargo**
### Description

- Create a table named `vets`
- Create a "join table" called `specializations`
- Create a "join table" called `visits`
- Insert data for `vets`
- Insert data for `specialties`
- Insert data for `visits`
- Write queries

### Screenshots

1. Who was the last animal seen by William Tatcher?
Screenshot from 2023-03-02 15-06-58
2. How many different animals did Stephanie Mendez see?
Screenshot from 2023-03-02 15-07-29
3. List all vets and their specialties, including vets with no specialties.
Screenshot from 2023-03-02 15-10-26
4. List all animals that visited Stephanie Mendez between April 1st and August 30th, 2020.
Screenshot from 2023-03-02 15-10-57

5. What animal has the most visits to vets?
Screenshot from 2023-03-02 15-11-19

6. Who was Maisy Smith's first visit?
Screenshot from 2023-03-02 15-12-51

7. Details for most recent visit: animal information, vet information, and date of visit.
Screenshot from 2023-03-02 15-13-25

8. How many visits were with a vet that did not specialize in that animal's species?
Screenshot from 2023-03-02 15-13-48

9. What specialty should Maisy Smith consider getting? Look for the species she gets the most.
Screenshot from 2023-03-02 15-14-58

### CODE REVIEW

**Review by Lucas-Masaba — CHANGES_REQUESTED** [review]
# Hello @utsargo  👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️ 
- [ ] Please add all the headers to your `README.md`. Currently, you are missing the future features header
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by utsargo** [comment]
@Lucas-Masaba this header was missing in the previous 3 pull requests. How come other reviewers did not notice that?

**Comment by utsargo** [comment]
@Lucas-Masaba can you please refer me to any documentation which states that having all the headers in readme is mandatory for code reviews?

**Comment by Lucas-Masaba** [comment]
Hello @utsargo , 

As code reviewers, we are instructed to ensure that your `README.md` has all the necessary headers the template provides to make it look professional. Here is a screenshot as proof that we are looking for this requirement. Let me know if this answer is satisfying enough. Sorry, for any inconvenience.
image

**Comment by utsargo** [comment]
@Lucas-Masaba Thank you very much, I understand. :)

**Comment by Lucas-Masaba** [comment]
Awesome @utsargo , happy coding 👨‍💻

**Review by Lucas-Masaba — APPROVED** [review]
# Hello @utsargo  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

almost-there

## Highlights 🍾 
- SQL is organised in their respective files.
- All queries are successful 🏄 
- Descriptive README 📜 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
